# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-PXML
version:      0.12
version_from: lib/Pod/PXML.pm
installdirs:  site
requires:
    HTML::Entities:                1
    Pod::Text:                     2.09
    Pod::Tree:                     1.06
    XML::Parser:                   2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
